yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Введите название группы',
    )
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Введите название группы',
    )

    def __str__(self) -> str:
        return str(self.title)


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст записи',
        help_text='Введите текст записи'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Название группы',
        help_text='Выберете название группы',
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name='Картинка',
        help_text='Загрузите картинку',
    )

    def __str__(self) -> str:
        return str(self.text[:15])

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

yatube/posts/forms.py
from django import forms
from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Follow, Group, Post, User

PAGE_PER_PAGE = 10


def paging(request, query, obj_per_page):
    paginator = Paginator(query, obj_per_page)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(20, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.select_related('author', 'group')
    page_obj = paging(request, post_list, PAGE_PER_PAGE)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_post(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paging(request, post_list, PAGE_PER_PAGE)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    post_author = get_object_or_404(User, username=username)
    post_list = post_author.posts.all()
    page_obj = paging(request, post_list, PAGE_PER_PAGE)
    me = request.user
    following = me.is_authenticated and post_author.following.exists()
    context = {
        'post_author': post_author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': CommentForm(),
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method != 'POST':
        form = PostForm()
        context = {
            'form': form,
            'is_edit': False,
        }
        return render(request, 'posts/post_create.html', context)
    form = PostForm(request.POST, files=request.FILES or None)
    if not form.is_valid():
        context = {
            'form': form,
            'is_edit': False,
        }
        return render(request, 'posts/post_create.html', context)
    form.instance.author = request.user
    form.save()
    return redirect('posts:profile', f'{request.user.get_username()}')


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    if request.method != 'POST':
        form = PostForm(instance=post)
        context = {
            'form': form,
            'is_edit': True,
        }
        return render(request, 'posts/post_create.html', context)
    form = PostForm(request.POST,
                    instance=post,
                    files=request.FILES or None)
    if not form.is_valid():
        return redirect('posts:post_detail', post_id=post_id)
    form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    follow = request.user.follower.all()
    follow_list = User.objects.filter(following__in=follow)
    posts = Post.objects.filter(author__in=(follow_list))
    page_obj = paging(request, posts, PAGE_PER_PAGE)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            author=author,
            user=request.user
        )
    return redirect('posts:profile', f'{username}')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    unfollow = get_object_or_404(Follow, user=request.user, author=author)
    unfollow.delete()
    return redirect('posts:profile', f'{username}')

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Последние обновления и{% endblock %}
{% block content %}
<h1>Последние обновления избраных авторов</h1>
{% include 'includes/switcher.html' %}
{% for post in page_obj %}
  {% include 'includes/post.html' %}
{% endfor %} 

{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
  {% block title %}
    Сайт группы {{ group.title }}
  {% endblock %}
  {% block content %} 
    <h1>{{ group }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
    {% endfor %} 
    {% include 'includes/paginator.html' %}
  {% endblock %}  

yatube/templates/posts/index.html
{% extends 'base.html' %}
  {% block content %}

    <h1>Последние обновления на сайте</h1>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
    {% endfor %} 

    {% include 'includes/paginator.html' %}
    
  {% endblock %}  

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
  {% block title %}
    {% if is_edit %}
      Редактировать пост.
    {% else %}
      Новый пост
    {% endif %}            
  {% endblock %}
  {% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">       
              {% if is_edit %}
                Редактировать пост.
              {% else %}
                Новый пост
              {% endif %}            
            </div>
            <div class="card-body">        
            <form method="post" action="{% if is_edit %}
                                          {% url 'posts:post_edit' post_id=form.instance.pk %}
                                        {% else %}
                                          {% url 'posts:post_create' %}
                                        {% endif %}"
                                        enctype="multipart/form-data" >
                {% csrf_token %}        
                  {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      {{ field.label }}
                      {% if field == form.text %}
                        <span class="required text-danger" >*</span>
                      {% endif %}
                    </label>
                    {{  field  }}
                    <small id="id_text-help" class="form-text text-muted">
                      {{  field.help_text }}
                    </small>
                  </div>
                  {% endfor %} 
                <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %} 
                </button>
                </div>
            </form>
            </div>
        </div>
        </div>
    </div>
  {% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
  {% load thumbnail %}
  {% block title %}
  Пост {{ post.text|truncatechars:30 }}
  {% endblock %}
  {% block content %}
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>               
          <li class="list-group-item">
            {% if post.group %}   
              Группа:{{ post.group.title }}</a>
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
          </li>            
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{  post.author.posts.all.count  }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if request.user  == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
          редактировать запись
        </a>
        {% endif %}
        {% if user.is_authenticated %}
        {% load user_filters %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.pk %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:'form-control' }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                {{ comment.created}}
                </p>
                <p>
                {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %}                
      </article>
    </div>     
  {% endblock %}


  

yatube/templates/posts/profile.html
{% extends 'base.html' %}
  {% block title %}
    Профайл пользователя {{ post_author.get_full_name }}
  {% endblock %}
  {% block content %}

    <h1>Все посты пользователя {{ post_author.get_full_name }}</h1>
    <h3>Всего постов: {{  post_author.posts.all.count }} </h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow'  post_author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow'  post_author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
    {% for post in page_obj %}
        {% include 'includes/post.html' %}
    {% endfor %} 
    {% include 'includes/paginator.html' %}

  {% endblock %}